spring:
  datasource:
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanbang_db?useSSL=false&serverTimezone=Asia/Shanghai
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 10s
      password: 123123
  jackson:
    time-zone: Asia/Shanghai
sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
springdoc:
  packages-to-scan: com.wanbang.controller
